[WIP] [FPGA Interchange]
antmicro/vtr-verilog-to-routing pull request #1
Opened 2021-10-22 14:53 UTC by mtdudek

#### Description
This PR adds initial support for reading and populating model, Gridlayout and device data

#### Motivation and Context
This change is necessary to add FPGA Interchange support 

#### How Has This Been Tested?
It wasn't

#### Types of changes
- [ ] Bug fix (change which fixes an issue)
- [x] New feature (change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

#### Checklist:
- [x] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

2021-10-22 15:04 UTC, acomodi requested changes
Overall looks good. I'd probably also remove all the `VTR_LOG` that are only relevant while implementing, but not necessary when merging. There is in facta a function called EchoArch (or similar) to print out all the contents of the architecture, once the various data structures are getting populated.

2021-10-22 15:04 UTC, acomodi commented on libs/libarchfpga/src/read_fpga_interchange_arch.cpp
> +static void ProcessModelPorts(t_model*, Netlist::CellDeclaration::Reader, List<Text, Kind::BLOB>::Reader, List<Netlist::Port, Kind::STRUCT>::Reader, std::set<std::pair<std::string, enum PORTS>>&, con
Might be worth just passing the device reader rather than the capnproto list objects which are quite hard to read, and quite misleading. We should try to keep the parameter list as contained as possible.

2021-10-22 15:04 UTC, acomodi commented on libs/libarchfpga/src/read_fpga_interchange_arch.cpp
> +static void warn_model_missing_timing(t_model*, const char*);
These functions are already present for the XML reading stuff. I think that we might check whether these can be made a bit more generic so as not to duplicate code.

2021-10-22 15:04 UTC, acomodi commented on libs/libarchfpga/src/read_fpga_interchange_arch.cpp
> +                break;
Missing default case will cause a warning at compile time

2021-10-22 15:04 UTC, acomodi commented on libs/libarchfpga/src/read_fpga_interchange_arch.cpp
> +        }
I don't think we need INOUT_PORT for the models. Not sure they can be actually handled. I'd keep it simple for now and remove the inout ports

2021-10-22 15:04 UTC, acomodi commented on libs/libarchfpga/src/read_fpga_interchange_arch.cpp
> +    }
Per the above comment, these might get deduplicated with the ones present in the XML reader.

2021-10-25 11:55 UTC, mtdudek commented on libs/libarchfpga/src/read_fpga_interchange_arch.cpp
> +                break;
Added default case.

2021-10-25 11:56 UTC, acomodi commented on libs/libarchfpga/src/read_xml_arch_file.cpp
> +            warn_model_missing_timing(temp, loc_data.filename_c_str(), loc_data.line(model));
I think `temp` should be left as `model` here

2021-10-25 11:57 UTC, acomodi commented on libs/libarchfpga/src/read_common_func.h
> +#ifndef READ_COMMON_FUNC_H
Not sure if we need a new file, as there is another one called `arch_util`. Maybe these functions can be added directly in there.

2021-10-25 12:00 UTC, mtdudek commented on libs/libarchfpga/src/read_xml_arch_file.cpp
> +            warn_model_missing_timing(temp, loc_data.filename_c_str(), loc_data.line(model));
t_model was temp in original version

2021-10-25 12:01 UTC, acomodi commented on libs/libarchfpga/src/read_xml_arch_file.cpp
> +            warn_model_missing_timing(temp, loc_data.filename_c_str(), loc_data.line(model));
Right, I misread it

2021-10-25 12:05 UTC, mtdudek commented on libs/libarchfpga/src/read_common_func.h
> +#ifndef READ_COMMON_FUNC_H
I don't think `arch_util` is right place for this functions, as it hold functions directly connected with `t_arch, t_model` and other structs used in `t_arch`. I think leaving it in `read_common_func.h` makes more sense, this functions are used in reading porccess only.

2021-10-25 12:10 UTC, acomodi commented on libs/libarchfpga/src/read_common_func.h
> +#ifndef READ_COMMON_FUNC_H
All right, makes sense

2021-10-28 08:04 UTC, closed without merging